### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by shameem356** [mahulchak/quickmerge#17]
Hello ,

I am facing a problem related to 'std::out_of_range'.When I ran quickmerge first time it worked fine with the following command1.But when I change the reference and query( Command 2 : swapped query & reference ) it showing the error std::out_of_range error.I am using latest build.Please let me know how can I solve the issue.

command 1
nucmer -l 100 -prefix out New_CspixV2gen.fa 0x_spix.fa
delta-filter -i 95 -r -q out.delta > out.rq.delta
quickmerge -d out.rq.delta -r New_CspixV2gen.fa -q 10x_spix.fa -hco 5.0 -c 1.5 -l 1000000 -ml 6000

command 2
nucmer -l 100 -prefix out 10x_spix.faNew_CspixV2gen.fa
delta-filter -i 95 -r -q out.delta > out.rq.delta
quickmerge -d out.rq.delta -r 10x_spix.fa -q New_CspixV2gen.fa -hco 5.0 -c 1.5 -l 1000000 -ml 6000

**Comment by mahulchak** [comment]
Is this the exact command you have used?

**Comment by shameem356** [comment]
Yes, I used the exact command in both cases.

**Comment by mahulchak** [comment]
In the quickmerge command line -q comes before -r. If you reverse the
sequence, you'll get that error.

**Comment by RxLoutre** [comment]
Hi Mahul !

I've got the same error using this command : 

`quickmerge -d out.rq.delta -q '/media/loutre/SUZUKII/assembly/falcon/falcon_cleaned_p_ctg.fasta' -r '/media/loutre/SUZUKII/assembly/canu/1-cleaned_names_canu3_suzukii.fasta' -hco 5.0 -c 1.5 -l 2000000 -ml 50000`

The problem was that I wasn't using the same files for nucmer command and quickmerge command. 

I let this here in case some will be not carefull enough like me and wonder what they have made wrong

**Comment by shameem356** [comment]
Hello @mahulchak ,

Its worked for me when I used -q before -r.Thank you so much for help.
