### ISSUE TITLE
Reg: mummer's newer version and alternatives

### ISSUE THREAD

**Issue by harish0201** [mahulchak/quickmerge#40]
Hi,

This is more of an enhancement/feature request than an issue!

Is there any reason that you are shipping mummer version 3 rather than the 4th one?

Also, given that I work with genomes > 2Gb normally, I have this query. Have you tried minimap2-> sam -> delta and then using those for quickmerge?

**Comment by mahulchak** [comment]
Hi Harish,

We haven't officially switched to mummer 4 yet because it is not as stable
as mummer 3. However, we will keep your request in mind and will see what
can be done. The mummer version included with quickmerge is 64 bit so you
can easily apply it to large genomes.

You can always run mummer yourself using the mummer in your system. You can
then run quickmerge on the delta file.

Mahul

**Comment by mahulchak** [comment]
We have not tried minimap2 -> sam->delta. We will look into that.

**Comment by harish0201** [comment]
Ah, alright! Thanks for the help. Currently the biggest bottleneck is the runtime of mummer to be honest. 

In the mean-time I'll check minimap2 and will correspond to you via emails if that is fine with you.

However, I'm closing the thread for the time being.
